name: "Setup osxcross"
author: mbround18
description: Setup osxcross for rust/other compilation projects.
branding:
  icon: 'aperture'  
  color: 'green'


inputs:
  osx-version:
    description: "Version of osx to use."
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: mkdir -p $GITHUB_ACTION_PATH/osxcross

    - shell: bash
      id: target
      run: |
        repeat(){
          for i in {1..90}; do echo -n "$1"; done
        }

        echo "::group::Disclaimer Click Here for Info"
        echo ""
        repeat "-"
        echo ""
        echo "The first time you run this it will take upwards of 9 minutes to compile. Subsequent builds are cached."
        echo ""
        repeat "-"
        echo ""
        echo "::endgroup::"


        echo "::group::Installing Deps"

        sudo apt-get update
        sudo apt-get install --no-install-recommends -y -qq clang gcc g++ zlib1g-dev libmpc-dev libmpfr-dev libgmp-dev  cmake libxml2-dev libssl-dev xz-utils 
        echo "::endgroup::"

        OSXCROSS_FOLDER="$(echo "$GITHUB_ACTION_PATH/osxcross" | sed 's/\.\/*//g')"

        echo "::group::Cloning osxcross"
        git clone https://github.com/tpoechtrager/osxcross "$OSXCROSS_FOLDER"
        echo "::endgroup::"

          

        # Check setup for osx version
        echo "::group::Fetching macosx SDK"
        FILE_NAME="MacOSX${{ inputs.osx-version }}.sdk.tar.xz"

        # Check joseluisq/macosx-sdks for release
        wget -nc "https://github.com/joseluisq/macosx-sdks/releases/download/${{ inputs.osx-version }}/${FILE_NAME}" -O "$OSXCROSS_FOLDER/tarballs/${FILE_NAME}"
        echo "::endgroup::"

        echo "OSXCROSS_TARGET=${OSXCROSS_FOLDER}/target" >> $GITHUB_ENV

    - uses: actions/cache@v3
      id: cache
      with:
        key: ${{ runner.os }}-osxcross-${{ inputs.osx-version }}
        path: |
          ${{ env.OSXCROSS_TARGET }}
          ${{ env.OSXCROSS_FOLDER }}/target/
          

    - shell: bash
      if: steps.cache.outputs.cache-hit != 'true'
      env:
        SDK_VERSION: "${{ inputs.osx-version }}"
        UNATTENDED: "yes"
      run: |
        cd "${GITHUB_ACTION_PATH}/osxcross"
        echo $PWD
        echo ${GITHUB_ACTION_PATH}
        ls -la
        ./build.sh
        ./build_gcc.sh

    - shell: bash
      run: |
        echo "::group::Setting up Bin files"
        OSXCROSS_FOLDER="$(echo "${GITHUB_ACTION_PATH}/osxcross" | sed 's/\.\/*//g')"
        echo "OSXCROSS Folder = ${OSXCROSS_FOLDER}"

        if [ ! -d "$OSXCROSS_FOLDER/target/bin" ]; then
          echo "Error! Failed to find ${OSXCROSS_FOLDER}/target/bin folder!"
          exit 1
        else
          if hash sudo 2>/dev/null; then
            sudo chmod +x $OSXCROSS_FOLDER/target/bin/*
          else
            chmod +x $OSXCROSS_FOLDER/target/bin/*
          fi    
        fi
          
        echo "::endgroup::"

        echo "::group::Finding Arch Name"
        echo "$OSXCROSS_FOLDER/target/bin" >> $GITHUB_PATH
        ARCH_TARGET="$(ls $OSXCROSS_FOLDER/target | grep apple)"
        echo "::endgroup::"

        echo "::group::Write meson cross file"
        cat << EOF > $GITHUB_ACTION_PATH/meson_osxcross.txt
        [constants]
        arch = '${ARCH_TARGET}'
        [binaries]
        c = arch + '-gcc'
        cpp = arch + '-g++'
        strip = arch + '-strip'
        pkg-config = arch  + '-pkg-config'
        ranlib = arch + '-gcc-ranlib'
        ar = arch + '-gcc-ar'
        
        [host_machine]
        system = 'darwin'
        cpu_family = 'x86_64'
        cpu = 'x86_64'
        endian = 'little'
        EOF
        echo "::endgroup::"
