name: Meson Build (Linux, macOS)

on:
  # Triggers the workflow when manually dispatched
  workflow_dispatch:
    inputs:
      upload_artefacts:
        description: "Upload build artefacts"
        type: boolean
        required: false
        default: false
      build_type:
        description: "Build Configuration"
        type: choice
        required: false
        default: "release"
        options:
          - "release"
          - "debug"
      debug_level:
        description: "Debug Level"
        type: choice
        required: false
        default: "release"
        options:
          - "release"
          - "minimal"
          - "full"
      new_release_version:
        type: string
        required: false
      osx-version:
        type: string
        required: false
        default: "11.1"
      macosx-deployment-target:
        type: string
        required: false
        default: "10.15"

  # Triggers the workflow when called by a top-level workflow
  workflow_call:
    inputs:
      upload_artefacts:
        type: boolean
        required: false
        default: false
      build_type: # "release" | "debug"
        type: string
        required: false
        default: "release"
      debug_level: # "full" | "minimal" | "release"
        type: string
        required: false
        default: "release"
      new_release_version:
        type: string
        required: false
      osx-version:
        type: string
        required: false
        default: "11.1"
      macosx-deployment-target:
        type: string
        required: false
        default: "10.15"

jobs:

  build-macos:
    runs-on: ubuntu-latest
    name: MacOS Build

    env:
      MACOSX_DEPLOYMENT_TARGET: ${{inputs.macosx-deployment-target}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: "Install Osxcross"
        id: osxcross
        uses: ./.github/actions/osxcross
        with:
          osx-version: ${{ inputs.osx-version }}
      
      - name: "Cache Dependencies"
        uses: actions/cache@v4
        with:
          key: ${{runner.os}}-${{inputs.osx-version}}-macports
          path: ${{env.OSXCROSS_FOLDER}}/target/macports

      - name: "Install Dependencies"
        env:
          OSXCROSS_MACPORTS_MIRROR: "https://packages.macports.org"
        run: |
          echo "::group::Installing mac deps"
          omp install libsdl2 onetbb lz4 libpng minizip luajit flac
          echo "::endgroup::"
          echo "::group::Installing meson"
          pip install meson ninja
          echo "::endgroup::"

      - name: Set Version
        if: ${{inputs.new_release_version}}
        uses: ./.github/actions/set_version
        with:
          new_release_version: ${{inputs.new_release_version}}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}-${{ matrix.os }}

      - name: Setup Meson
        env:
          LDFLAGS: "-static-libgcc -static-libstdc++"
        run: |
          meson setup --cross-file=${{steps.osxcross.outputs.meson-osxcross}} --buildtype=${{inputs.build_type}} -Ddebug_type=${{inputs.debug_level}} -Db_lto=false build

      - name: Configure for App Bundle
        if: ${{inputs.upload_artefacts}}
        env:
          LDFLAGS: "-static-libgcc -static-libstdc++"
        run: |
          meson configure \
          -Dinstall_data=false -Dinstall_runner=false -Dfmod_dir=Contents/Frameworks \
          --bindir=Contents/MacOS \
          --prefix="/" \
          build

      - name: Build
        env:
          LDFLAGS: "-static-libgcc -static-libstdc++"
        run: |
          meson compile -C build

      - name: Create App Bundle
        if: ${{inputs.upload_artefacts}}
        run: |
          DESTDIR="/tmp/Cortex Command.app" meson install -C build

      - name: Tar files
        if: ${{inputs.upload_artefacts}}
        run: |
          cd /tmp/
          tar -cvf CortexCommand.tar "Cortex Command.app"

      - name: Move artefact
        if: ${{inputs.upload_artefacts}}
        run: cp /tmp/CortexCommand.tar .

      - name: Artifact Deploy
        if: ${{inputs.upload_artefacts}}
        uses: actions/upload-artifact@v3
        with:
          name: CortexCommand (macOS)
          path: |
            CortexCommand.tar
          if-no-files-found: error