name: Meson Build (Linux, macOS)

on:
  # Triggers the workflow when manually dispatched
  workflow_dispatch:
    inputs:
      upload_artefacts:
        description: "Upload build artefacts"
        type: boolean
        required: false
        default: false
      build_type:
        description: "Build Configuration"
        type: choice
        required: false
        default: "release"
        options:
          - "release"
          - "debug"
      debug_level:
        description: "Debug Level"
        type: choice
        required: false
        default: "release"
        options:
          - "release"
          - "minimal"
          - "full"
      new_release_version:
        type: string
        required: false
      osx-version:
        type: string
        required: false
        default: "11.1"
      macosx-deployment-target:
        type: string
        required: false
        default: "10.15"

  # Triggers the workflow when called by a top-level workflow
  workflow_call:
    inputs:
      upload_artefacts:
        type: boolean
        required: false
        default: false
      build_type: # "release" | "debug"
        type: string
        required: false
        default: "release"
      debug_level: # "full" | "minimal" | "release"
        type: string
        required: false
        default: "release"
      new_release_version:
        type: string
        required: false
      osx-version:
        type: string
        required: false
        default: "11.1"
      macosx-deployment-target:
        type: string
        required: false
        default: "10.15"

jobs:

  build-macos:
    runs-on: ubuntu-latest
    name: MacOS Build

    env:
      MACOSX_DEPLOYMENT_TARGET: ${{inputs.macosx-deployment-target}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3

      - name: "Install Osxcross"
        id: osxcross
        uses: ./.github/actions/osxcross
        with:
          osx-version: ${{ inputs.osx-version }}
